sudo: required

branches:
  except:
    - weblate
services:
  - docker

dist: jammy
language: node_js
node_js:
  - 20
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker run --rm -u $(id -u) -v $(pwd):/app opensourcepos/composer:ci4 composer install
  - version=$(grep application_version app/Config/App.php | sed "s/.*=\s'\(.*\)';/\1/g")
  - sed -i "s/commit_sha1 = 'dev'/commit_sha1 = '$rev'/g" app/Config/OSPOS.php
  - echo "$version-$branch-$rev" 
  - npm version "$version-$branch-$rev" --force || true
  - npm ci && npm install -g gulp && npm run build 
  - docker build . --target ospos -t ospos
  - docker build app/Database/ -t "jekkos/opensourcepos:sql-$TAG"
env:
  global:
  - BRANCH=$(echo ${TRAVIS_BRANCH} | sed s/feature\\///)
  - TAG=${TRAVIS_TAG:-$BRANCH}
  - date=`date +%Y%m%d%H%M%S` && branch=${TRAVIS_BRANCH} && rev=`git rev-parse --short=6 HEAD` 
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker tag "ospos:latest"
    "jekkos/opensourcepos:$TAG" && docker push "jekkos/opensourcepos:$TAG" && docker push "jekkos/opensourcepos:sql-$TAG"
  - gulp compress
  - mv dist/opensourcepos.tar.gz "dist/opensourcepos.$version.$rev.tgz"
  - mv dist/opensourcepos.zip "dist/opensourcepos.$version.$rev.zip"
deploy:
  - provider: npm
    edge: true
    src: dist/opensourcepos.$version.$rev.tgz
    registry: https://npm.pkg.github.com
    auth_method: auth 
    email: jeroen@steganos.dev
    api_token:
      secure: "DNPJOrT51wdO0BAbkX2hKowdXYh7x8d43xvAw7eVfOslyBPiv6Bb/1QdC2Bpnlqe0WiJVS5hvBTMrJ+vSDK5i/l8jA+ZoI6ms1+P1DQ6sBBMBQI2fuvRCrJj+Fp3WnaduZb/N7R+FqdKQwD/ZORyhzJ4whtHkrO8uC7cY/wlacU="

    on:
      all_branches: true
  - provider: releases
    edge: true
    file: dist/opensourcepos.$version.$rev.zip
    name: "OpensourcePos $version"
    release_notes_file: CHANGELOG.md
    prerelease: true

    user: jekkos
    overwrite: true
    api_key:
      secure: "DNPJOrT51wdO0BAbkX2hKowdXYh7x8d43xvAw7eVfOslyBPiv6Bb/1QdC2Bpnlqe0WiJVS5hvBTMrJ+vSDK5i/l8jA+ZoI6ms1+P1DQ6sBBMBQI2fuvRCrJj+Fp3WnaduZb/N7R+FqdKQwD/ZORyhzJ4whtHkrO8uC7cY/wlacU="

    on:
      tags: true
      branch: master
